title: MizzleAa
description: blog
author: MizzleAa
github: https://github.com/mizzleaa
about: Python, AI, Data Scientist, Others, Let's do all we can.!
disqus_shortname: mizzleaa
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/mizzleaa"

share:
  twitter_username: "" 
  fb_appid: ""

urls:
    - text: About
      url: /about/
    - text: Projects
      url: /projects/
    - text: Category
      url: /category/
      
url: "https://mizzleaa.github.io"
baseurl: ""
paginate: 10
per_page: 10
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
